type: eventgateway
version: 0.2.0
core: 0.2.x

description: "Event Gateway Serverless Component."
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  event:
    type: string
    required: true
  path:
    type: string
    required: true
  method:
    type: string
    required: false
  cors:
    type: boolean
  space:
    type: string
    required: true
  eventGatewayApiKey:
    type: string
    displayName: Event gateway API Access Key
    description: API key of your event gateway space
    required: false
  lambdaArn:
    type: string
    required: true
    displayName: Lambda function ARN
    description: The ARN of the lambda function being called by the event gateway
    example: arn:aws:lambda:us-east-1:123456789012:function:ProcessKinesisRecords

outputTypes:
  subscriptionId:
    type: string
    description: The generated subscription id
  url:
    type: string
    description: The generated URL
